//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.BhulekhOdisha {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BhulekhOdisha.OdishaCropInsuranceSoap")]
    public interface OdishaCropInsuranceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgriCensusRORData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable AgriCensusRORData(string distCode, int villCensusCode, string khataNo, string plotNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgriCensusRORData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> AgriCensusRORDataAsync(string distCode, int villCensusCode, string khataNo, string plotNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OdishaCropInsuranceSoapChannel : CommercialAgriEnterprise.BhulekhOdisha.OdishaCropInsuranceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OdishaCropInsuranceSoapClient : System.ServiceModel.ClientBase<CommercialAgriEnterprise.BhulekhOdisha.OdishaCropInsuranceSoap>, CommercialAgriEnterprise.BhulekhOdisha.OdishaCropInsuranceSoap {
        
        public OdishaCropInsuranceSoapClient() {
        }
        
        public OdishaCropInsuranceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OdishaCropInsuranceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OdishaCropInsuranceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OdishaCropInsuranceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable AgriCensusRORData(string distCode, int villCensusCode, string khataNo, string plotNo) {
            return base.Channel.AgriCensusRORData(distCode, villCensusCode, khataNo, plotNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> AgriCensusRORDataAsync(string distCode, int villCensusCode, string khataNo, string plotNo) {
            return base.Channel.AgriCensusRORDataAsync(distCode, villCensusCode, khataNo, plotNo);
        }
    }
}
