//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.BhulekhOdishaR {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BhulekhOdishaR.AgriCensusServiceSoap")]
    public interface AgriCensusServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgriRORData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable AgriRORData(string distCode, int tehCode, int villCode, string khataNo, string plotNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgriRORData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> AgriRORDataAsync(string distCode, int tehCode, int villCode, string khataNo, string plotNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AgriCensusServiceSoapChannel : CommercialAgriEnterprise.BhulekhOdishaR.AgriCensusServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgriCensusServiceSoapClient : System.ServiceModel.ClientBase<CommercialAgriEnterprise.BhulekhOdishaR.AgriCensusServiceSoap>, CommercialAgriEnterprise.BhulekhOdishaR.AgriCensusServiceSoap {
        
        public AgriCensusServiceSoapClient() {
        }
        
        public AgriCensusServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgriCensusServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgriCensusServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgriCensusServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable AgriRORData(string distCode, int tehCode, int villCode, string khataNo, string plotNo) {
            return base.Channel.AgriRORData(distCode, tehCode, villCode, khataNo, plotNo);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> AgriRORDataAsync(string distCode, int tehCode, int villCode, string khataNo, string plotNo) {
            return base.Channel.AgriRORDataAsync(distCode, tehCode, villCode, khataNo, plotNo);
        }
    }
}
