//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public long TCode { get; set; }
        public string IPAddress { get; set; }
        public string UserID { get; set; }
        public string Url { get; set; }
        public string DeviceType { get; set; }
        public string Model { get; set; }
        public string Manufacture { get; set; }
        public string OS { get; set; }
        public string Browser { get; set; }
        public string ScreenSize { get; set; }
        public System.DateTime DateTime { get; set; }
        public string Action { get; set; }
        public string Attack { get; set; }
        public string Param { get; set; }
        public string Mode { get; set; }
    }
}
