//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeneficiaryDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BeneficiaryDetail()
        {
            this.BeneFiciaryLandRecordDetails = new HashSet<BeneFiciaryLandRecordDetail>();
            this.BeneficiaryMemberDetails = new HashSet<BeneficiaryMemberDetail>();
            this.BLODPRLogs = new HashSet<BLODPRLog>();
            this.BLOFeasibilityLogs = new HashSet<BLOFeasibilityLog>();
            this.BLORegdLogs = new HashSet<BLORegdLog>();
            this.CashFlowStatements = new HashSet<CashFlowStatement>();
            this.DPRLogs = new HashSet<DPRLog>();
            this.GoAheads = new HashSet<GoAhead>();
            this.IntegratedProjectDetails = new HashSet<IntegratedProjectDetail>();
            this.Payments = new HashSet<Payment>();
            this.ProfitabilityProjections = new HashSet<ProfitabilityProjection>();
            this.RegistrationLogs = new HashSet<RegistrationLog>();
        }
    
        public string ReferenceNo { get; set; }
        public string FarmerID { get; set; }
        public string FVoterIDNo { get; set; }
        public string FAadhaarNo { get; set; }
        public string RelationApplicantName { get; set; }
        public string RelationWithFIDType { get; set; }
        public Nullable<int> RelationWithFID { get; set; }
        public string RAadhaarNo { get; set; }
        public string RVoterIDNo { get; set; }
        public string MobileNo { get; set; }
        public System.DateTime DateOfRegd { get; set; }
        public string BeneficiaryType { get; set; }
        public Nullable<int> NoOfMember { get; set; }
        public string FirmName { get; set; }
        public Nullable<int> GroupTypeCode { get; set; }
        public decimal PercentageOfSubsidy { get; set; }
        public string Pin { get; set; }
        public string CorrespondenceAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string PreviousExperience { get; set; }
        public string EmailID { get; set; }
        public string HighestEducationalQualificationCode { get; set; }
        public byte[] CastGraduationCertificate { get; set; }
        public decimal AnnualIncome { get; set; }
        public string PresentOccupation { get; set; }
        public string NICBlockCode { get; set; }
        public string NICDistrictCode { get; set; }
        public string RegistrationStatus { get; set; }
        public Nullable<decimal> RegistrationAmount { get; set; }
        public string PaymentStatus { get; set; }
        public byte[] LandPdf1 { get; set; }
        public byte[] LandPdf2 { get; set; }
        public Nullable<decimal> SubsidyAmount { get; set; }
    
        public virtual BankLoanStatu BankLoanStatu { get; set; }
        public virtual EducationalQualification EducationalQualification { get; set; }
        public virtual GroupType GroupType { get; set; }
        public virtual BeneficiaryDocument BeneficiaryDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeneFiciaryLandRecordDetail> BeneFiciaryLandRecordDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeneficiaryMemberDetail> BeneficiaryMemberDetails { get; set; }
        public virtual BeneficiaryProjectDetail BeneficiaryProjectDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BLODPRLog> BLODPRLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BLOFeasibilityLog> BLOFeasibilityLogs { get; set; }
        public virtual BLORecord BLORecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BLORegdLog> BLORegdLogs { get; set; }
        public virtual CapitalInvestment CapitalInvestment { get; set; }
        public virtual CapitalInvestmentAnimalPlant CapitalInvestmentAnimalPlant { get; set; }
        public virtual CapitalInvestmentCivilConstruction CapitalInvestmentCivilConstruction { get; set; }
        public virtual CapitalInvestmentElectrification CapitalInvestmentElectrification { get; set; }
        public virtual CapitalInvestmentLand CapitalInvestmentLand { get; set; }
        public virtual CapitalInvestmentMiscellaneou CapitalInvestmentMiscellaneou { get; set; }
        public virtual CapitalInvestmentPlantMachinery CapitalInvestmentPlantMachinery { get; set; }
        public virtual CapitalInvestmentWaterSupply CapitalInvestmentWaterSupply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashFlowStatement> CashFlowStatements { get; set; }
        public virtual CollectorRecord CollectorRecord { get; set; }
        public virtual DDABackToBLOLog DDABackToBLOLog { get; set; }
        public virtual DDARecord DDARecord { get; set; }
        public virtual DNOBackToBLOLog DNOBackToBLOLog { get; set; }
        public virtual DNORecord DNORecord { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DPRLog> DPRLogs { get; set; }
        public virtual DPRStatu DPRStatu { get; set; }
        public virtual RecurringExpenditure RecurringExpenditure { get; set; }
        public virtual FeasibilityReport FeasibilityReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoAhead> GoAheads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntegratedProjectDetail> IntegratedProjectDetails { get; set; }
        public virtual IntegratedProjectLog IntegratedProjectLog { get; set; }
        public virtual KeyBusinessMatrix KeyBusinessMatrix { get; set; }
        public virtual MeansOfFinance MeansOfFinance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfitabilityProjection> ProfitabilityProjections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegistrationLog> RegistrationLogs { get; set; }
    }
}
