//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeneficiaryProjectDetail
    {
        public string ReferenceNo { get; set; }
        public string DepartmentCode { get; set; }
        public string ProjectTypeCode { get; set; }
        public string FinanceType { get; set; }
        public string ProductToBeProducedOrMarketed { get; set; }
        public string IsCISAvailedPreviously { get; set; }
        public string CISProjectTypeCode { get; set; }
        public string CISLocation { get; set; }
        public string CISAvailedYear { get; set; }
        public string CISFinanceType { get; set; }
        public Nullable<decimal> CISAmount { get; set; }
        public byte[] CISBankClearanceCertificate { get; set; }
        public string ApproximateCost { get; set; }
        public decimal OwnContribution { get; set; }
        public Nullable<decimal> BankLoan { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public string CapacityUnit { get; set; }
        public string BankCode { get; set; }
        public string BranchCode { get; set; }
        public byte[] BankConsentLetter { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual ProjectType ProjectType { get; set; }
        public virtual ProjectType ProjectType1 { get; set; }
        public virtual BeneficiaryDetail BeneficiaryDetail { get; set; }
    }
}
