//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeneficiaryCompletion
    {
        public string GoAheadNumber { get; set; }
        public string IsEmploymentCreated { get; set; }
        public System.DateTime StartOrCompletionDate { get; set; }
        public decimal BuildingCost { get; set; }
        public decimal ElectrificationCost { get; set; }
        public decimal MachineryCost { get; set; }
        public decimal InfrastructureCost { get; set; }
        public decimal FencingCost { get; set; }
        public decimal PlantOrAnimalCost { get; set; }
        public Nullable<decimal> OtherCost { get; set; }
        public string Place { get; set; }
        public System.DateTime CompletionDate { get; set; }
        public System.DateTime UserDateTime { get; set; }
        public string IPAddress { get; set; }
        public string FinancialYear { get; set; }
    
        public virtual GoAhead GoAhead { get; set; }
    }
}
