//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLODPRLog
    {
        public string ReferenceNo { get; set; }
        public string BLOUserName { get; set; }
        public System.DateTime UserDateTime { get; set; }
        public Nullable<decimal> Development { get; set; }
        public Nullable<decimal> Fencing { get; set; }
        public Nullable<decimal> LandTotal { get; set; }
        public Nullable<decimal> Building { get; set; }
        public Nullable<decimal> Shed { get; set; }
        public Nullable<decimal> OfficeCumStore { get; set; }
        public Nullable<decimal> Godown { get; set; }
        public Nullable<decimal> PlantArea { get; set; }
        public Nullable<decimal> OtherNecessaryConstruction { get; set; }
        public Nullable<decimal> CivilConstructionTotal { get; set; }
        public Nullable<decimal> WellOrRiver { get; set; }
        public Nullable<decimal> PumpPipeLine { get; set; }
        public Nullable<decimal> Tank { get; set; }
        public Nullable<decimal> SprinklerFogger { get; set; }
        public Nullable<decimal> WaterSupplyTotal { get; set; }
        public Nullable<decimal> InstallationFitting { get; set; }
        public Nullable<decimal> Transformer { get; set; }
        public Nullable<decimal> DGSet { get; set; }
        public Nullable<decimal> ElectrificationTotal { get; set; }
        public Nullable<decimal> Equipment { get; set; }
        public Nullable<decimal> ManualOrMotor { get; set; }
        public Nullable<decimal> PlantMachineryTotal { get; set; }
        public Nullable<decimal> AnimalPlantLiveStock { get; set; }
        public string LiveStockType { get; set; }
        public Nullable<decimal> PoultryBreeder { get; set; }
        public Nullable<decimal> BroodFish { get; set; }
        public Nullable<decimal> Plant { get; set; }
        public Nullable<decimal> AnimalPlantTotal { get; set; }
        public Nullable<decimal> FixedAsset { get; set; }
        public Nullable<decimal> MiscellaneousLivestock { get; set; }
        public Nullable<decimal> Bird { get; set; }
        public Nullable<decimal> Cultivation { get; set; }
        public Nullable<decimal> MiscellaneousTotal { get; set; }
        public Nullable<decimal> RawMaterial { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<decimal> Maintenance { get; set; }
        public Nullable<decimal> RecurringExpenditureTotal { get; set; }
        public Nullable<decimal> TotalCapitalInvestmentCost { get; set; }
        public Nullable<decimal> TotalProjectCost { get; set; }
        public Nullable<decimal> OwnInvestment { get; set; }
        public string OwnInvestmentRemark { get; set; }
        public Nullable<decimal> TermLoan { get; set; }
        public string TermLoanRemark { get; set; }
        public Nullable<decimal> WorkingCapitalLoan { get; set; }
        public string WorkingCapitalLoanRemark { get; set; }
        public Nullable<decimal> OtherSource { get; set; }
        public string OtherSourceRemark { get; set; }
        public Nullable<decimal> MeansOfFinanceTotal { get; set; }
        public string ProfitabilityProjectionYear { get; set; }
        public Nullable<decimal> GrossRevenue { get; set; }
        public Nullable<decimal> TotalExpenditure { get; set; }
        public Nullable<decimal> GrossProfit { get; set; }
        public Nullable<decimal> NetProfit { get; set; }
        public string CashFlowStatementYear { get; set; }
        public Nullable<decimal> TotalCashInflow { get; set; }
        public Nullable<decimal> TotalCashOutflow { get; set; }
        public Nullable<decimal> NetCashInflow { get; set; }
        public Nullable<decimal> BreakEvenPoint { get; set; }
        public Nullable<decimal> DSCR { get; set; }
        public Nullable<decimal> IRR { get; set; }
        public string IPAddress { get; set; }
        public string FinancialYear { get; set; }
    
        public virtual BeneficiaryDetail BeneficiaryDetail { get; set; }
    }
}
