//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLOFeasibilityLog
    {
        public string ReferenceNo { get; set; }
        public string BLOUserName { get; set; }
        public System.DateTime UserDateTime { get; set; }
        public bool PreviousExperience { get; set; }
        public bool RoadConnectivity { get; set; }
        public bool ElectrificationStatus { get; set; }
        public bool PollutionControlClearanceStatus { get; set; }
        public bool BankConsentLetterStatus { get; set; }
        public decimal DistanceFromVillage { get; set; }
        public decimal SelfFinance { get; set; }
        public decimal UncensoredLoan { get; set; }
        public decimal MarginComponent { get; set; }
        public string IPAddress { get; set; }
        public string FinancialYear { get; set; }
    
        public virtual BeneficiaryDetail BeneficiaryDetail { get; set; }
    }
}
