//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLORecord
    {
        public string ReferenceNo { get; set; }
        public int BLOStatus { get; set; }
        public Nullable<bool> RegdStatus { get; set; }
        public Nullable<bool> DPRStatus { get; set; }
        public Nullable<bool> PaymentStatus { get; set; }
        public Nullable<int> MobileUploadStatus { get; set; }
        public Nullable<System.DateTime> BLODate { get; set; }
        public string RejectionReason { get; set; }
        public string BLOUserName { get; set; }
        public string IPAddress { get; set; }
        public string FinancialYear { get; set; }
    
        public virtual BeneficiaryDetail BeneficiaryDetail { get; set; }
    }
}
