//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BLORegdLog
    {
        public string ReferenceNo { get; set; }
        public string BLOUserName { get; set; }
        public System.DateTime UserDateTime { get; set; }
        public string FirmName { get; set; }
        public Nullable<int> GroupTypeCode { get; set; }
        public string PreviousExperience { get; set; }
        public Nullable<decimal> AnnualIncome { get; set; }
        public string PresentOccupation { get; set; }
        public string Pin { get; set; }
        public string CorrespondenceAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string EmailID { get; set; }
        public string ProductToBeProducedOrMarketed { get; set; }
        public string FinanceType { get; set; }
        public string ApproximateCost { get; set; }
        public Nullable<decimal> OwnContribution { get; set; }
        public Nullable<decimal> BankLoan { get; set; }
        public string BankCode { get; set; }
        public string BranchCode { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public byte[] CastGraduationCertificate { get; set; }
        public byte[] BankConsentLetter { get; set; }
        public byte[] LandPdf1 { get; set; }
        public byte[] LandPdf2 { get; set; }
        public byte[] IdentityProof { get; set; }
        public Nullable<decimal> SubsidyAmount { get; set; }
        public string IPAddress { get; set; }
        public string FinancialYear { get; set; }
    
        public virtual BeneficiaryDetail BeneficiaryDetail { get; set; }
    }
}
