//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapitalInvestmentAnimalPlant
    {
        public string ReferenceNo { get; set; }
        public Nullable<decimal> LiveStock { get; set; }
        public string LiveStockType { get; set; }
        public decimal PoultryBreeder { get; set; }
        public decimal BroodFish { get; set; }
        public decimal Plant { get; set; }
        public decimal Total { get; set; }
    
        public virtual BeneficiaryDetail BeneficiaryDetail { get; set; }
    }
}
