//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapitalInvestmentWaterSupply
    {
        public string ReferenceNo { get; set; }
        public decimal WellOrRiver { get; set; }
        public decimal PumpPipeLine { get; set; }
        public decimal Tank { get; set; }
        public decimal SprinklerFogger { get; set; }
        public decimal Total { get; set; }
    
        public virtual BeneficiaryDetail BeneficiaryDetail { get; set; }
    }
}
