//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckPasswordStatu
    {
        public string UserName { get; set; }
        public bool PasswordStatus { get; set; }
        public System.DateTime DateTime { get; set; }
        public string IPAddress { get; set; }
        public string FinancialYear { get; set; }
    }
}
