//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CollectorRecord
    {
        public string ReferenceNo { get; set; }
        public int CollectorStatus { get; set; }
        public Nullable<int> CollectorUpdateStatus { get; set; }
        public Nullable<int> LotNo { get; set; }
        public Nullable<System.DateTime> DateOfMeeting { get; set; }
        public Nullable<System.TimeSpan> TimeOfMeeting { get; set; }
        public string IPAddress { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> UserDateTime { get; set; }
        public string FinancialYear { get; set; }
        public Nullable<System.DateTime> UpdatedDOM { get; set; }
        public Nullable<System.TimeSpan> UpdatedTOM { get; set; }
        public string UpdatedIPAddress { get; set; }
        public string UpdatedUserName { get; set; }
        public Nullable<System.DateTime> UpdatedUserDateTime { get; set; }
        public string UpdatedFinancialYear { get; set; }
    
        public virtual BeneficiaryDetail BeneficiaryDetail { get; set; }
    }
}
