//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DDARecord
    {
        public string ReferenceNo { get; set; }
        public int DDAStatus { get; set; }
        public Nullable<int> BackToBLOStatus { get; set; }
        public Nullable<int> IntegratedFarmingStatus { get; set; }
        public Nullable<System.DateTime> IntegratedFarmingDate { get; set; }
        public Nullable<System.DateTime> DDAStatusDate { get; set; }
        public string DDARejectionReason { get; set; }
        public string UserName { get; set; }
        public string IPAddress { get; set; }
        public string FinancialYear { get; set; }
    
        public virtual BeneficiaryDetail BeneficiaryDetail { get; set; }
    }
}
