//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNODistrictMapping
    {
        public string UserID { get; set; }
        public int DistrictCode { get; set; }
        public string DeptCode { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual LGDDistrict LGDDistrict { get; set; }
    }
}
