//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNODetailLog
    {
        public string DNOUserID { get; set; }
        public System.DateTime DisableDateTime { get; set; }
        public string DNOName { get; set; }
        public string DNOMobileNo { get; set; }
        public byte[] DNOSignature { get; set; }
        public string DeptCode { get; set; }
        public int DistrictCode { get; set; }
        public string IPAddress { get; set; }
        public string UserName { get; set; }
        public System.DateTime UserDateTime { get; set; }
        public string FinancialYear { get; set; }
        public int IsActive { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual LGDDistrict LGDDistrict { get; set; }
    }
}
