//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNORecord
    {
        public string ReferenceNo { get; set; }
        public int DNOStatus { get; set; }
        public Nullable<int> BackToBLOStatus { get; set; }
        public Nullable<System.DateTime> DNODateTime { get; set; }
        public string RejectionReason { get; set; }
        public string DNOUserName { get; set; }
        public string IPAddress { get; set; }
        public string FinancialYear { get; set; }
    
        public virtual BeneficiaryDetail BeneficiaryDetail { get; set; }
    }
}
