//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FARMERDBEntities : DbContext
    {
        public FARMERDBEntities()
            : base("name=FARMERDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<LGBlock> LGBlocks { get; set; }
        public virtual DbSet<LGDistrict> LGDistricts { get; set; }
        public virtual DbSet<LGGp> LGGps { get; set; }
        public virtual DbSet<LGVillage> LGVillages { get; set; }
        public virtual DbSet<M_FARMER_REGISTRATION> M_FARMER_REGISTRATION { get; set; }
        public virtual DbSet<M_PDS_BANKBRANCH> M_PDS_BANKBRANCH { get; set; }
        public virtual DbSet<M_PDS_FARMERBANK> M_PDS_FARMERBANK { get; set; }
        public virtual DbSet<M_PDS_RELATIONSHIP> M_PDS_RELATIONSHIP { get; set; }
        public virtual DbSet<PDS_BLOCKMASTER> PDS_BLOCKMASTER { get; set; }
        public virtual DbSet<PDS_DISTRICTMASTER> PDS_DISTRICTMASTER { get; set; }
        public virtual DbSet<PDS_GPMASTER> PDS_GPMASTER { get; set; }
        public virtual DbSet<PDS_VILLAGEMASTER> PDS_VILLAGEMASTER { get; set; }
        public virtual DbSet<Tbl_Bank> Tbl_Bank { get; set; }
        public virtual DbSet<Tbl_Category> Tbl_Category { get; set; }
        public virtual DbSet<Tbl_Gender> Tbl_Gender { get; set; }
        public virtual DbSet<Tbl_Branch> Tbl_Branch { get; set; }
    
        public virtual ObjectResult<FarmerFamilyDetails_Result> FarmerFamilyDetails(string vchfarmercode, Nullable<int> intrelationid)
        {
            var vchfarmercodeParameter = vchfarmercode != null ?
                new ObjectParameter("vchfarmercode", vchfarmercode) :
                new ObjectParameter("vchfarmercode", typeof(string));
    
            var intrelationidParameter = intrelationid.HasValue ?
                new ObjectParameter("intrelationid", intrelationid) :
                new ObjectParameter("intrelationid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FarmerFamilyDetails_Result>("FarmerFamilyDetails", vchfarmercodeParameter, intrelationidParameter);
        }
    
        public virtual ObjectResult<FarmerFamilyRelation_Result> FarmerFamilyRelation(string vchfarmercode)
        {
            var vchfarmercodeParameter = vchfarmercode != null ?
                new ObjectParameter("vchfarmercode", vchfarmercode) :
                new ObjectParameter("vchfarmercode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<FarmerFamilyRelation_Result>("FarmerFamilyRelation", vchfarmercodeParameter);
        }
    }
}
