//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeasibilityReport
    {
        public string ReferenceNo { get; set; }
        public bool PreviousExperience { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public byte[] Photo { get; set; }
        public bool RoadConnectivity { get; set; }
        public decimal DistanceFromVillage { get; set; }
        public bool ElectrificationStatus { get; set; }
        public bool PollutionControlClearanceStatus { get; set; }
        public decimal SelfFinance { get; set; }
        public decimal UncensoredLoan { get; set; }
        public decimal MarginComponent { get; set; }
        public bool BankConsentLetterStatus { get; set; }
        public bool Status { get; set; }
        public string UserName { get; set; }
    
        public virtual BeneficiaryDetail BeneficiaryDetail { get; set; }
    }
}
