//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegratedProjectDetail
    {
        public string ReferenceNo { get; set; }
        public string ProjectTypeCode { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public string CapacityUnit { get; set; }
        public int IPBLOStatus { get; set; }
        public string BLOUserName { get; set; }
    
        public virtual BeneficiaryDetail BeneficiaryDetail { get; set; }
    }
}
