//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegratedProjectLog
    {
        public string PreviousReferenceNo { get; set; }
        public string PreviousUserName { get; set; }
        public string NewUserName { get; set; }
        public string PreviousDeptCode { get; set; }
        public string NewDeptCode { get; set; }
        public System.DateTime UserDateTime { get; set; }
        public string IPAddress { get; set; }
        public string FinancialYear { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Department Department1 { get; set; }
        public virtual BeneficiaryDetail BeneficiaryDetail { get; set; }
    }
}
