//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LGDDistrict
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LGDDistrict()
        {
            this.BeneFiciaryLandRecordDetails = new HashSet<BeneFiciaryLandRecordDetail>();
            this.BLODetailEntries = new HashSet<BLODetailEntry>();
            this.CollectorDistrictMappings = new HashSet<CollectorDistrictMapping>();
            this.DNODetailEntries = new HashSet<DNODetailEntry>();
            this.DNODistrictMappings = new HashSet<DNODistrictMapping>();
            this.LGDBlocks = new HashSet<LGDBlock>();
            this.LGDGPs = new HashSet<LGDGP>();
            this.LGDVillages = new HashSet<LGDVillage>();
            this.Targets = new HashSet<Target>();
            this.TargetLogs = new HashSet<TargetLog>();
            this.DNODetailLogs = new HashSet<DNODetailLog>();
        }
    
        public int DistrictCode { get; set; }
        public string DistrictName { get; set; }
        public int RevenueDistrictCode { get; set; }
        public string PDSDistrictName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeneFiciaryLandRecordDetail> BeneFiciaryLandRecordDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BLODetailEntry> BLODetailEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollectorDistrictMapping> CollectorDistrictMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DNODetailEntry> DNODetailEntries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DNODistrictMapping> DNODistrictMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LGDBlock> LGDBlocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LGDGP> LGDGPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LGDVillage> LGDVillages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Target> Targets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TargetLog> TargetLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DNODetailLog> DNODetailLogs { get; set; }
    }
}
