//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LGDGP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LGDGP()
        {
            this.BeneFiciaryLandRecordDetails = new HashSet<BeneFiciaryLandRecordDetail>();
        }
    
        public int DistrictCode { get; set; }
        public int BlockCode { get; set; }
        public int GPCode { get; set; }
        public string GPName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeneFiciaryLandRecordDetail> BeneFiciaryLandRecordDetails { get; set; }
        public virtual LGDBlock LGDBlock { get; set; }
        public virtual LGDDistrict LGDDistrict { get; set; }
    }
}
