//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LGDVillage
    {
        public int DistrictCode { get; set; }
        public int BlockCode { get; set; }
        public Nullable<int> GPCode { get; set; }
        public int VillageCode { get; set; }
        public string VillageName { get; set; }
        public int Status { get; set; }
    
        public virtual LGDBlock LGDBlock { get; set; }
        public virtual LGDDistrict LGDDistrict { get; set; }
    }
}
