//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LGGp
    {
        public Nullable<int> Dist_Code { get; set; }
        public Nullable<int> Block_Code { get; set; }
        public int Gp_Code { get; set; }
        public string Gp_Name { get; set; }
    
        public virtual LGBlock LGBlock { get; set; }
    }
}
