//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_FARMER_REGISTRATION
    {
        public int INTFARMERID { get; set; }
        public string CHFARMERTYPE { get; set; }
        public string VCHFARMERCODE { get; set; }
        public string VCHEXISTFRCODE { get; set; }
        public string VCHPACSCODE { get; set; }
        public string VCHDISTID { get; set; }
        public string VCHBLOCKID { get; set; }
        public string VCHGPID { get; set; }
        public string VCHVILLAGEID { get; set; }
        public Nullable<int> INTTITLE { get; set; }
        public string VCHFARMERNAME { get; set; }
        public string VCHFATHERNAME { get; set; }
        public Nullable<int> INTRELATION { get; set; }
        public Nullable<int> INTGENDER { get; set; }
        public Nullable<int> INTCATEGOGY { get; set; }
        public Nullable<System.DateTime> DTMDOB { get; set; }
        public Nullable<int> INTAGE { get; set; }
        public string CHAGESTATUS { get; set; }
        public string VCHVOTERIDCARDNO { get; set; }
        public string VCHAADHARNO { get; set; }
        public string VCHMOBILENO { get; set; }
        public Nullable<int> INTFAMILYMEMBERS { get; set; }
        public string VCHACCHOLDERNM { get; set; }
        public string VCHACCOUNTNO { get; set; }
        public Nullable<int> INTBANKID { get; set; }
        public Nullable<int> INTBRANCHID { get; set; }
        public string VCHIFSCCODE { get; set; }
        public string CHACCSTATUS { get; set; }
        public Nullable<System.DateTime> DTMACCVERIFIEDON { get; set; }
        public string VCHPINCODE { get; set; }
        public Nullable<int> INTDELETEDFLAG { get; set; }
        public Nullable<int> INTCREATEDBY { get; set; }
        public Nullable<System.DateTime> DTMCREATEDON { get; set; }
        public Nullable<int> INTUPDATEDBY { get; set; }
        public Nullable<System.DateTime> DTMUPDATEDON { get; set; }
        public Nullable<int> INTPFMSVERIFIED { get; set; }
        public Nullable<int> INTREJECTED { get; set; }
        public string NICFARMERID { get; set; }
        public Nullable<bool> PFMSST { get; set; }
        public string CHAPFMSSTATUS { get; set; }
        public string ADHARSTATUS { get; set; }
        public Nullable<System.DateTime> ADHARUPDT { get; set; }
    }
}
