//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PDS_RELATIONSHIP
    {
        public int INTRELATIONID { get; set; }
        public string VCHRELATION { get; set; }
        public string VCHORIYAREL { get; set; }
        public Nullable<int> INTSEQUENCE { get; set; }
        public Nullable<int> intFRStatus { get; set; }
    }
}
