//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeansOfFinance
    {
        public string ReferenceNo { get; set; }
        public decimal OwnInvestment { get; set; }
        public string OwnInvestmentRemark { get; set; }
        public decimal TermLoan { get; set; }
        public string TermLoanRemark { get; set; }
        public decimal WorkingCapitalLoan { get; set; }
        public string WorkingCapitalLoanRemark { get; set; }
        public decimal OtherSource { get; set; }
        public string OtherSourceRemark { get; set; }
        public decimal TotalAmount { get; set; }
    
        public virtual BeneficiaryDetail BeneficiaryDetail { get; set; }
    }
}
