//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDS_DISTRICTMASTER
    {
        public string int_DistrictID { get; set; }
        public string vch_DistrictName { get; set; }
        public string vch_DistrictNameOr { get; set; }
        public string vch_DistrictCode { get; set; }
        public Nullable<int> int_AdminId { get; set; }
        public Nullable<int> int_RDCType { get; set; }
        public string vch_RDC { get; set; }
        public Nullable<System.DateTime> dtmCreatedOn { get; set; }
    }
}
