//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDS_BLOCKMASTER
    {
        public string int_BlockID { get; set; }
        public string int_DistrictID { get; set; }
        public string vch_BlockName { get; set; }
        public string vch_BlockNameOr { get; set; }
        public string vch_BlockCode { get; set; }
        public string vch_DistrictCode { get; set; }
        public string vchBlockType { get; set; }
        public Nullable<int> intBlockType { get; set; }
        public Nullable<int> intPPASS { get; set; }
        public Nullable<System.DateTime> dtmCreatedOn { get; set; }
        public string NIC_BlockCode { get; set; }
    }
}
