//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDS_GPMASTER
    {
        public string int_GPID { get; set; }
        public string int_BlockID { get; set; }
        public string vch_GPName { get; set; }
        public string vch_GPNameOr { get; set; }
        public string vch_GPCode { get; set; }
        public string vch_BlockCode { get; set; }
        public Nullable<System.DateTime> dtmCreatedOn { get; set; }
    }
}
