//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDS_VILLAGEMASTER
    {
        public string int_VillageID { get; set; }
        public string int_GPID { get; set; }
        public string vch_VillageName { get; set; }
        public string vch_VillageNameOr { get; set; }
        public string vch_censusCode { get; set; }
        public string vch_RefCode { get; set; }
        public Nullable<System.DateTime> dtmCreatedOn { get; set; }
        public Nullable<int> lgvillage_code { get; set; }
        public Nullable<bool> G_status { get; set; }
    }
}
