//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfitabilityProjection
    {
        public string ReferenceNo { get; set; }
        public string Year { get; set; }
        public decimal GrossRevenue { get; set; }
        public decimal TotalExpenditure { get; set; }
        public decimal GrossProfit { get; set; }
        public decimal NetProfit { get; set; }
    
        public virtual BeneficiaryDetail BeneficiaryDetail { get; set; }
    }
}
