//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectType()
        {
            this.BeneficiaryProjectDetails = new HashSet<BeneficiaryProjectDetail>();
            this.BeneficiaryProjectDetails1 = new HashSet<BeneficiaryProjectDetail>();
            this.Targets = new HashSet<Target>();
            this.TargetLogs = new HashSet<TargetLog>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public string DepartmentCode { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> MinCapacity { get; set; }
        public string CapacityUnit { get; set; }
        public Nullable<decimal> CostPerUnitGenMale { get; set; }
        public Nullable<decimal> CostPerUnitSCSTFemale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeneficiaryProjectDetail> BeneficiaryProjectDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeneficiaryProjectDetail> BeneficiaryProjectDetails1 { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Target> Targets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TargetLog> TargetLogs { get; set; }
    }
}
