//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rVillage
    {
        public string VCode { get; set; }
        public string DCode { get; set; }
        public string TCode { get; set; }
        public string veName { get; set; }
        public string voName { get; set; }
    
        public virtual rDistrict rDistrict { get; set; }
    }
}
