//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Target
    {
        public int DistrictCode { get; set; }
        public string ProjectTypeCode { get; set; }
        public int GeneralValue { get; set; }
        public int SCValue { get; set; }
        public int STValue { get; set; }
        public string FinancialYear { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime UserDateTime { get; set; }
    
        public virtual LGDDistrict LGDDistrict { get; set; }
        public virtual ProjectType ProjectType { get; set; }
    }
}
