//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialAgriEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Bank
    {
        public string Dist_Code { get; set; }
        public string Bank_Code { get; set; }
        public string Bank_Name { get; set; }
        public Nullable<int> PFMSStatus { get; set; }
        public Nullable<int> IntegrationStatus { get; set; }
    }
}
